### ISSUE TITLE
Documentation links broken

### ISSUE THREAD

**Issue by trusktr** [jeromeetienne/AR.js#444]
Many links in the docs (README and blog posts) forward to https://daqri.com. :(

F.e.: https://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_training

**Comment by nicolocarpignoli** [comment]
Yes, there is a PR merged on dev for this.
As soon as I can I will move those commits also on master.

**Comment by nicolocarpignoli** [comment]
done, new readme available on master :)

**Comment by matyunya** [comment]
Many are still broken
https://jeromeetienne.github.io/AR.js-docs/misc/EXAMPLES.html

**Comment by nicolocarpignoli** [comment]
ar.js-docs is deprecated, please refer to readme of ar.js
